<?php
	// Calls the specific JS files
	$this->headScript()->appendFile($this->basePath() . '/js/my-submissions.js', null, 'append');
?>
<div class="container">
	<div class="content">
		<div class="page-header">
			<h1 class="catch"><?php echo $this->translate('My submissions'); ?></h1>
		</div>
		
		<div class="row" style="padding-left:10px;padding-right:10px;">
			<?php if ($this->subs): ?>
			<table class="table table-striped table-bordered">
				<tr>
					<th><?php echo $this->translate('Title'); ?></th>
					<th><?php echo $this->translate('Conference'); ?></th>
					<th><?php echo $this->translate('Date sent'); ?></th>
					<th><?php echo $this->translate('Accepted'); ?></th>
					<th><?php echo $this->translate('Manage'); ?></th>
				</tr>
				<?php foreach ($this->subs as $sub): ?>
				<tr>
					<td class="col-sm-6"><?php echo $sub['title']; ?></td>
					<td><?php echo $sub['short_name']; ?></td>
					<td class="col-sm-2">
						<?php
							$date = $this->extractDate($sub['date_sent']);
							printf('%s/%s/%s', $date['day'], $date['month'], $date['short_year']);
						?>
					</td>
					<td class="col-sm-1"><?php echo $sub['accepted'] ? $this->translate('Yes') : $this->translate('No'); ?></td>
					<td class="col-sm-1">
						<div class="btn-group">
							<?php
								// Get translations
								$edit = $this->translate('Edit');
								$speakers = $this->translate('Speakers');
							?>
							<!-- Edit -->
							<a class="btn btn-small" href="<?php echo $this->url('cfp/inner', array('action' => 'submit', 'id' => $sub['conference_id'], 'edit' => $sub['submission_id'])); ?>" alt="<?php echo $edit; ?>" title="<?php echo $edit; ?>"><i class="icon-pencil"></i></a>
							<!-- Speakers -->
							<a class="btn btn-small" alt="<?php echo $speakers; ?>" title="<?php echo $speakers; ?>" rel="speakers" href="#<?php echo $sub['submission_id']; ?>"><i class="icon-user"></i></a>
						</div>
					</td>
				</tr>
				<?php endforeach; ?>
			</table>
			<?php else: ?>
			<p><?php echo $this->translate('No submissions found.'); ?></p>
			<p><a href="<?php echo $this->url('cfp'); ?>"><?php echo $this->translate('Click here to see open call for papers'); ?></a>.</p>
			<?php endif; ?>
		</div>
	</div>

	<!-- Speakers Modal -->
	<div class="modal hide fade" id="speakers" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3><?php echo $this->translate('Speakers'); ?></h3>
		</div>
		<div id="modal-content" class="modal-body">

			
			<div class="row">
				<table id="speakers_table" class="table table-striped table-bordered">
					<tr>
						<th><?php echo $this->translate('Speaker'); ?></th>
						<th><?php echo $this->translate('Email'); ?></th>
						<th><?php echo $this->translate('Status'); ?></th>
						<th class="col-sm-1">&nbsp;</th>
					</tr>
				</table>
			</div>
			<div class="row right-text">
				<form class="form-inline">
					<input id="speaker_email" type="text" class="input col-sm-6" placeholder="<?php echo $this->translate("Speaker's Email"); ?>">
					<button id="speaker_add" class="btn btn-success"><i class="icon-plus-sign icon-white"></i> <?php echo $this->translate('Add speaker'); ?></button>
				</form>
			</div>
		</div>
		<div class="modal-footer">
			<button class="btn btn-primary" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Close'); ?></button>
		</div>
	</div>
	
</div>