<div class="container">
	<div class="content">
		<div class="page-header">
			<h1 class="catch"><?php echo $this->translate('My submissions'); ?></h1>
		</div>
		
		<div class="row-fluid">
			<?php if ($this->subs): ?>
			<table class="table table-striped table-bordered">
				<tr>
					<th><?php echo $this->translate('Title'); ?></th>
					<th><?php echo $this->translate('Conference'); ?></th>
					<th><?php echo $this->translate('Date sent'); ?></th>
					<th><?php echo $this->translate('Accepted'); ?></th>
				</tr>
				<?php foreach ($this->subs as $sub): ?>
				<tr>
					<td class="span6"><?php echo $sub['title']; ?></td>
					<td><?php echo $sub['short_name']; ?></td>
					<td class="span2">
						<?php
							$date = $this->extractDate($sub['date_sent']);
							printf('%s/%s/%s', $date['day'], $date['month'], $date['short_year']);
						?>
					</td>
					<td class="span1"><?php echo $sub['accepted'] ? $this->translate('Yes') : $this->translate('No'); ?></td>
				</tr>
				<?php endforeach; ?>
			</table>
			<?php else: ?>
			<p><?php echo $this->translate('No submissions found.'); ?></p>
			<p><a href="<?php echo $this->url('cfp'); ?>"><?php echo $this->translate('Click here to see open call for papers'); ?></a>.</p>
			<?php endif; ?>
		</div>
	</div>
	
</div>