<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

// Workaround for POedit extractor
_('Username or Email');
_('Password');
?>
<div class="container">
	<div class="content">
	
		<div class="page-header">
			<h1 class="catch"><?php echo $this->translate('Sign In'); ?></h1>
		</div>

		<div class="row-fluid">
			<?php echo $this->form()->openTag($form) ?>

			    <dl class="zend_form">
			        <?php echo $this->formElementErrors($form->get('identity')) ?>

			        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
			        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

			        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
			        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

			        <?php if ($this->redirect): ?>
			            <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
			        <?php endif ?>

			        <dd><?php echo $this->formButton($form->get('submit')->setAttribute('class','btn btn-primary')) ?></dd>
			    </dl>

			<?php echo $this->form()->closeTag() ?>

			<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
		</div>
	
	</div>
</div>
