<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/recovery'));
$form->setAttribute('method', 'post');

// Workaround for POedit extractor
_('Username or Email');
_('Recover password');
?>
<div class="container">
	<div class="content">
	
		<div class="page-header">
			<h1 class="catch"><?php echo $this->translate('Password recovery'); ?></h1>
		</div>

		<div class="row-fluid">
			<?php echo $this->form()->openTag($form) ?>

			    <dl class="zend_form">
			        <?php echo $this->formElementErrors($form->get('identity')) ?>

			        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
			        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

			        <dd><?php echo $this->formButton($form->get('submit')->setAttribute('class','btn btn-primary')) ?></dd>
			    </dl>

			<?php echo $this->form()->closeTag() ?>
		</div>
	
	</div>
</div>
