<div class="container-fluid">
	<div class="row-fluid">
		<!-- Content -->
		<div class="content">
			<div class="page-header">
				<h1 class="catch"><?php echo $this->translate('Password recovery'); ?></h1>
			</div>
			
			<div>
				<p class="lead"><?php echo $this->translate('An email has been sent to you containing a link to change your password. You should receive it shortly.'); ?></p>
				<p class="lead"><?php echo $this->translate('If you are having problems, contact a system administrator.'); ?></p>
				<p><a href="<?php echo $this->url('home'); ?>" class="btn"><i class="icon-circle-arrow-left"></i> <?php echo $this->translate('Click here to return to the main page'); ?></a></p>
			</div>
		</div>
	</div>
</div>