<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/recovery/hash', array('hash' => $this->hash)));
$form->setAttribute('method', 'post');

// Workaround for POedit extractor
_('New password (at least 6 characters)');
_('Set new password');
?>
<div class="container">
	<div class="content">
	
		<div class="page-header">
			<h1 class="catch"><?php echo $this->translate('Password recovery'); ?></h1>
		</div>

		<div class="row-fluid">
			<?php echo $this->form()->openTag($form) ?>

			    <dl class="zend_form">
			        <?php echo $this->formElementErrors($form->get('pass')) ?>

			        <dt><?php echo $this->formLabel($form->get('pass')) ?></dt>
			        <dd><?php echo $this->formInput($form->get('pass')) ?></dd>

			        <dd><?php echo $this->formButton($form->get('submit')->setAttribute('class','btn btn-primary')) ?></dd>
			    </dl>

			<?php echo $this->form()->closeTag() ?>
		</div>
	
	</div>
</div>
