<?php
if (!$this->enableRegistration) {
    echo $this->translate('Registration is disabled');
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');

// Workaround for POedit extractor
_('Username');
_('Email');
_('Display Name');
_('Password Verify');
?>

<div class="container">
	<div class="content">
	
		<div class="page-header">
			<h1 class="catch"><?php echo $this->translate('Register'); ?></h1>
		</div>

		<div class="row-fluid">
			<?php echo $this->form()->openTag($form) ?>
			    <dl class="zend_form">
			    <?php foreach ($form as $element): ?>
			        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
			            <dt><?php echo $this->formLabel($element) ?></dt>
			        <?php endif ?>
			        <?php if ($element instanceof Zend\Form\Element\Button): ?>
			            <dd><?php echo $this->formButton($element->setAttribute('class','btn btn-primary')) ?></dd>
			        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
			            <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
			        <?php else: ?>
			            <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
			        <?php endif ?>
			    <?php endforeach ?>
			    </dl>
			    <?php if ($this->redirect): ?>
			        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
			    <?php endif ?>
			<?php echo $this->form()->closeTag() ?>
		</div>
	
	</div>
</div>