<div class="container">
	<div class="content">
	
		<div class="page-header">
			<h1 class="catch"><?php echo $this->translate('Conferences management'); ?></h1>
			<p class="byline"><?php echo $conference->name . ' / ' . $this->translate('Attendees'); ?></p>
		</div>
		<div class="row-fluid">
			<p><?php printf('<strong>%s:</strong> %s', $this->translate('Number of attendees'), $this->attendees->count()); ?></p>
		</div>
		<?php if ($this->attendees->count()): ?>
		<div class="row-fluid">
			<table class="table table-striped table-bordered">
				<tr>
					<th><?php echo $this->translate('Name'); ?></th>
					<th><?php echo $this->translate('Email'); ?></th>
					<th><?php echo $this->translate('Registration date'); ?></th>
					<th><?php echo $this->translate('Accreditation date'); ?></th>
					<th><?php echo $this->translate('Disclose email'); ?></th>
					<?php /* <th class="span1">&nbsp;</th> */ ?>
				</tr>
				<?php foreach ($this->attendees as $att): ?>
				<tr>
					<td><?php echo $att['display_name']; ?></td>
					<td><?php echo $att['email']; ?></td>
					<td><?php $date = $this->extractDate($att['register']); printf('%s/%s/%s', $date['day'], $date['month'], $date['year']); ?></td>
					<td><?php if ($att['accreditation']) { $date = $this->extractDate($att['accreditation']); printf('%s/%s/%s', $date['day'], $date['month'], $date['year']); } else { echo $this->translate('Not yet'); }?></td>
					<td><?php echo $att['disclose_email'] ? $this->translate('Yes') : $this->translate('No'); ?></td>
					<?php /*<td class="center-text">
						<div class="btn-group">
							<!-- Details -->
							<a href="#" title="" alt="" class="btn btn-small"><i class="icon-eye-open"></i></a>
							<!-- Speakers -->
							<a href="#" title="" alt="" class="btn btn-small"><i class="icon-user"></i></a>
							<!-- Approve -->
							<a href="#" title="" alt="" class="btn btn-small btn-success"><i class="icon-ok icon-white"></i></a>
							<!-- Remove -->
							<a href="#" title="" alt="" class="btn btn-small btn-danger"><i class="icon-remove icon-white"></i></a>
						</div>
					</td> */ ?>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
		<?php endif; ?>
	</div>
	
</div>