<div class="container">
	<div class="content">
	
		<div class="page-header">
			<h1 class="catch"><?php echo $this->translate('Conferences management'); ?></h1>
			<p class="byline"><?php echo $conference->name . ' / ' . $this->translate('Submissions'); ?></p>
		</div>

		<div class="row-fluid">
			<table class="table table-striped table-bordered">
				<tr>
					<th><?php echo $this->translate('Title'); ?></th>
					<th><?php echo $this->translate('Track'); ?></th>
					<th><?php echo $this->translate('Submited by'); ?></th>
					<th><?php echo $this->translate('Email'); ?></th>
					<th><?php echo $this->translate('Duration'); ?></th>
					<th><?php echo $this->translate('Date sent'); ?></th>
					<th><?php echo $this->translate('Accepted'); ?></th>
					<th class="span1">&nbsp;</th>
				</tr>
				<?php foreach ($this->submissions as $sub): ?>
				<tr>
					<td><?php echo $sub['title']; ?></td>
					<td><?php echo $sub['track_name']; ?></td>
					<td><?php echo $sub['user']; ?></td>
					<td><?php echo $sub['email']; ?></td>
					<td><?php echo $sub['duration'] == 4 ? $sub['duration'] . 'h+' : $sub['duration'] . 'h'; ?></td>
					<td><?php $date = $this->extractDate($sub['date_sent']); printf('%s/%s/%s', $date['day'], $date['month'], $date['year']); ?></td>
					<td><?php echo $sub['accepted'] ? $this->translate('Yes') : $this->translate('No'); ?></td>
					<td class="center-text">
						<div class="btn-group">
							<!-- Details -->
							<a href="#" title="" alt="" class="btn btn-small"><i class="icon-eye-open"></i></a>
							<!-- Speakers -->
							<a href="#" title="" alt="" class="btn btn-small"><i class="icon-user"></i></a>
							<!-- Approve -->
							<a href="#" title="" alt="" class="btn btn-small btn-success"><i class="icon-ok icon-white"></i></a>
							<!-- Remove -->
							<a href="#" title="" alt="" class="btn btn-small btn-danger"><i class="icon-remove icon-white"></i></a>
						</div>
					</td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</div>
	
</div>