<div class="container-fluid">
	<div class="row-fluid">
		<!-- Content -->
		<div class="content">
			<div class="page-header">
				<h1>&nbsp;<i class="big-icon-notes-2"></i> <?php echo $this->translate('Call for Papers'); ?></h1>
			</div>
			
			<div>
				<p class="lead"><?php echo $this->translate('Sorry. This call is already closed.'); ?>

				<p><a href="<?php echo $this->url('home'); ?>" class="btn"><i class="icon-circle-arrow-left"></i> <?php echo $this->translate('Click here to return to the main page'); ?></a>
			</div>
		</div>
	</div>
</div>