<div class="container-fluid">
	<div class="row-fluid">
		<!-- Content -->
		<div class="content">
			<div class="page-header">
				<h1>&nbsp;<i class="big-icon-notes-2"></i> <?php echo $this->translate('Call for Papers'); ?> <small><?php echo $this->translate('Submit your proposal'); ?></small></h1>
			</div>
			
			<div>
				<ul class="nav nav-list nav-no-padding">
					<?php
						if ($this->conferences):
							foreach ($this->conferences as $conf):?>
					
						<li><a href="<?php echo $this->url('cfp/inner', array('action' => 'submit', 'id' => $conf['conference_id'])); ?>"><i class="icon-calendar"></i>
								(<?php
									$first_day = $this->extractDate($conf['cfp_opened']);
									$last_day = $this->extractDate($conf['cfp_closed']);
									echo $first_day['day'] . '/' . $first_day['month'];
									if ($conf['cfp_opened'] != $conf['cfp_closed'])
										echo ' - ' . $last_day['day'] . '/' . $last_day['month'];
								?>)
								<?php echo $conf['name']; ?>
						</a></li>
					
						<?php
							endforeach;
						else:
							echo $this->translate('No call for papers.');
						endif;
					?>
				</ul>

			</div>
		</div>
	</div>
</div>