<div class="container-fluid">
	<div class="row-fluid">
		<!-- Content -->
		<div class="content">
			<div class="page-header">
				<h1>&nbsp;<i class="big-icon-notes-2"></i> <?php echo $this->translate('Call for Papers'); ?> <small><?php echo $this->translate('Submit your proposal'); ?></small></h1>
			</div>
			
			<div>
				<p class="lead"><?php echo $this->translate('Your proposal has been submitted successfully. Wait for the evaluation period and you will be contacted if your proposal is approved.'); ?>

				<p><?php echo $this->translate('If you want to submit another proposal,'); ?> <a href="<?php echo $this->url('cfp'); ?>"><?php echo $this->translate('click here')?></a>.
			</div>
		</div>
	</div>
</div>