<?php
	// Calls the specific JS files
	$this->headScript()->appendFile($this->basePath() . '/js/my-submissions.js', null, 'append');
?>
<div class="container">
	<div class="content">
		<div class="page-header">
			<h1 class="catch"><?php echo $this->translate('My conferences'); ?></h1>
		</div>
		
		<div class="row" style="padding-left:10px;padding-right:10px;">
			<?php if ($this->registered): ?>
				<h2><?php echo $this->translate('Conferences you enrolled'); ?></h2>
				<table class="table table-striped table-bordered">
					<tr>
						<th class="col-sm-9"><?php echo $this->translate('Conference'); ?></th>
						<th class="col-sm-2"><?php echo $this->translate('Registered in'); ?></th>
						<th class="col-sm-1"><?php echo $this->translate('Details'); ?></th>
					</tr>
					<?php foreach ($this->registered as $reg): ?>
					<tr>
						<td><?php echo $reg['name']; ?></td>
						<td>
							<?php
								$date = $this->extractDate($reg['register']);
								printf('%s/%s/%s', $date['day'], $date['month'], $date['short_year']);
							?>
						</td>
						<td class="center-text">
							<div class="btn-group">
								<?php
									// Get translations
									$details = $this->translate('Conference details');
								?>
								<!-- Conference details -->
								<a class="btn btn-small" href="<?php echo $this->url('conferences/inner', array('action' => 'view', 'id' => $reg['conference_id'])); ?>" alt="<?php echo $details; ?>" title="<?php echo $details; ?>"><i class="icon-eye-open"></i></a>
							</div>
						</td>
					</tr>
					<?php endforeach; ?>
				</table>				
			<?php endif; ?>
			
			<?php if ($this->accreditated): ?>
				<h2><?php echo $this->translate('Conferences you\'ve been'); ?></h2>
				<table class="table table-striped table-bordered">
					<tr>
						<th class="col-sm-9"><?php echo $this->translate('Conference'); ?></th>
						<th class="col-sm-2"><?php echo $this->translate('Registered in'); ?></th>
						<th class="col-sm-1"><?php echo $this->translate('Details'); ?></th>
					</tr>
					<?php foreach ($this->accreditated as $reg): ?>
					<tr>
						<td><?php echo $reg['name']; ?></td>
						<td>
							<?php
								$date = $this->extractDate($reg['register']);
								printf('%s/%s/%s', $date['day'], $date['month'], $date['short_year']);
							?>
						</td>
						<td class="center-text">
							<div class="btn-group">
								<?php
									// Get translations
									$details = $this->translate('Conference details');
								?>
								<!-- Conference details -->
								<a class="btn btn-small" href="<?php echo $this->url('conferences/inner', array('action' => 'view', 'id' => $reg['conference_id'])); ?>" alt="<?php echo $details; ?>" title="<?php echo $details; ?>"><i class="icon-eye-open"></i></a>
							</div>
						</td>
					</tr>
					<?php endforeach; ?>
				</table>				
			<?php endif; ?>

			<?php if (!$this->registered && !$this->accreditated): ?>
			<p><?php echo $this->translate('You didn\'t attend any conference.'); ?></p>
			<p><a href="<?php echo $this->url('conferences'); ?>"><?php echo $this->translate('Click here to see open conferences'); ?></a>.</p>
			<?php endif; ?>
		</div>
	</div>

	<!-- Speakers Modal -->
	<div class="modal hide fade" id="speakers" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3><?php echo $this->translate('Speakers'); ?></h3>
		</div>
		<div id="modal-content" class="modal-body">

			
			<div class="row">
				<table id="speakers_table" class="table table-striped table-bordered">
					<tr>
						<th><?php echo $this->translate('Speaker'); ?></th>
						<th><?php echo $this->translate('Email'); ?></th>
						<th><?php echo $this->translate('Status'); ?></th>
						<th class="col-sm-1">&nbsp;</th>
					</tr>
				</table>
			</div>
			<div class="row right-text">
				<form class="form-inline">
					<input id="speaker_email" type="text" class="input col-sm-6" placeholder="<?php echo $this->translate("Speaker's Email"); ?>">
					<button id="speaker_add" class="btn btn-success"><i class="icon-plus-sign icon-white"></i> <?php echo $this->translate('Add speaker'); ?></button>
				</form>
			</div>
		</div>
		<div class="modal-footer">
			<button class="btn btn-primary" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Close'); ?></button>
		</div>
	</div>
	
</div>