<div class="alert alert-info">
	<strong>Atenção:</strong> Ao utilizar este sistema você está participando de um período de testes. Esta aplicação
	ainda está em desenvolvimento e pode apresentar erros inesperados durante sua execução. Caso isso ocorra, peço que entre em contato com <strong>rafael@phpit.com.br</strong> informando o erro. Obrigado!
</div>
      <div class="row-fluid">
		<div class="span12">
          <div class="hero-unit">
	
			<!-- Bigger title for desktop version -->
			<img src="user_content/logo.png" class="span2 logo" alt="TcheLinux - Eventos" description="TcheLinux - Eventos">
            <h1>TcheLinux - Eventos</h1>
            <p>O TcheLinux, Grupo de Usuários de Software Livre do Rio Grande do Sul, é um grupo de voluntários que preza pela ação social constante, trazendo o ideal participativo do desenvolvimento de Software Livre para o dia-a-dia dos profissionais, estudantes e interessados em tecnologias livres do estado, ao buscar continuamente a organização de eventos gratuitos e encontros informais para a discussão técnica e troca de experiências entre seus membros. Participe!</p>
            <p><a class="btn btn-primary btn-large" href="<?php echo $this->url('zfcuser'); ?>"><?php echo $this->translate('Sign In') . ' &raquo;' ?></a></p>
          </div>

		<?php /*?>

          <div class="row-fluid">
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
          <div class="row-fluid">
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->

*/